name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs:
      ingress-url:
        description: "Provide the Ingress URL"
        required: true
        type: string
    secrets:
      token:
        required: true
     
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - env:
          URL: '${{ needs.dev-deploy.outputs.APP_INGRESS_URL }}'
        run: |
          curl https://$URL/live -s -k | jq -r .status | grep -i live
